name: Bump version

on:
  push:
    branches: [develop]

jobs:
  bump:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        DIR=$(pwd)
        cd ../
        python -m pip install --upgrade pip
        if [ -f ${DIR}/requirements.txt ]; then pip install -r ${DIR}/requirements-dev.txt ; fi
        bump2version patch  msa_sdk/__init__.py

    - name: Commit bump version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Commit bump version
        commit_user_name: Eduardo Ferreira (bot)
        commit_user_email: efeubiqube@ubiqube.com
        commit_author: Eduardo Ferreira <efeubiqube@ubiqube.com>
        push_options: --force
