name: Bump version

on:
  push:
    branches: [develop]

jobs:
  bump:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Bump version
        run: |
          bump2version patch --commit msa_sdk/__init__.py
